services:
  app:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_NAME: "Tukutix"
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: "http://localhost"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ticketing
      DB_USERNAME: postgres
      DB_PASSWORD: password
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/backend/storage:/var/www/storage

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api"
      port: 3000
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - frontend

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
